# Site settings

title: Your awesome title
email: martinvalchev2@gmail.com
description: sadasdas
baseurl: "/MWhairstyles" # /MWhairstyles
url: "" # the base hostname & protocol for your site, e.g. http://example.com

destination: "docs"

github_username:  martinvalchevv

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


 exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - scss
  - gulpfile.js
  - package.json
  - package-lock.json
