# Site settings

title: Салон за красота
email: martinvalchev2@gmail.com
description: Дизайн на сайт салон за красота
baseurl: "/MWhairstyles" # /MWhairstyles
url: "" # the base hostname & protocol for your site, e.g. http://example.com

destination: "docs"

github_username:  martinvalchevv

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - docs
  - node_modules
  - scss
  - .gitignore
  - package-lock.json
